---
- name: Download opensnitch core package
  ansible.builtin.get_url:
    url: https://github.com/evilsocket/opensnitch/releases/download/v1.8.0/opensnitch-1.8.0-1.x86_64.rpm
    dest: /tmp/opensnitch-1.8.0-1.x86_64.rpm
    mode: '0644'
  become: true

- name: Install opensnitch core package
  ansible.builtin.dnf:
    name: /tmp/opensnitch-1.8.0-1.x86_64.rpm
    state: latest
    disable_gpg_check: true
  become: true

- name: Remove opensnitch core package archive
  ansible.builtin.file:
    path: /tmp/opensnitch-1.8.0-1.x86_64.rpm
    state: absent
  become: true

- name: Download opensnitch UI package
  ansible.builtin.get_url:
    url: https://github.com/evilsocket/opensnitch/releases/download/v1.8.0/opensnitch-ui-1.8.0-1.noarch.rpm
    dest: /tmp/opensnitch-ui-1.8.0-1.noarch.rpm
    mode: '0644'
  become: true

- name: Install opensnitch UI package
  ansible.builtin.dnf:
    name: /tmp/opensnitch-ui-1.8.0-1.noarch.rpm
    state: latest
    disable_gpg_check: true
  become: true

- name: Remove opensnitch UI package archive
  ansible.builtin.file:
    path: /tmp/opensnitch-ui-1.8.0-1.noarch.rpm
    state: absent
  become: true
